### ISSUE TITLE
[BUG] Agent names cannot contain punctuation / spaces / etc

### ISSUE THREAD

**Issue by meermanr** [state-of-the-art/BlendNet#132]
### Issue description:

I'm using the `local` provider and thus manually adding my personal computers to the agents of BlendNet. When I give them names like "Robert's MBP" I get the following error in Blender's STDIO:

    ERROR: Communication exception - check the remote service for errors "https://Roberts-MBP.lan:8443/api/v1/agent/Robert's MBA/config": (<class 'http.client.InvalidURL'>, InvalidURL('URL can\'t contain control characters. "/api/v1/agent/Robert\'s MBA/config" (found at least \' \')'), <traceback object at 0x12c83ac30>)
    
This doesn't happen if I instead call my agent "Roberts-MBP": note the lack of apostrophe or space.

### Environment:
* **Application version**: blendnet-0.3.6-27de9c6
* **Blender client version**: 2.91.0
* **Blender worker version**: 2.91.0
* **OS**: MacOS 10.15.7

### Steps to reproduce:

1. Run Blender
2. Open Render tab in Properties pane
3. Click on `+` next to `Agents (0)` within "BlendNet Render (local)" section
4. Enter

 - Name: "Two words"
 - Address: Roberts-MBP.lan

5. See error:

```
ERROR: Communication exception - check the remote service for errors "https://Roberts-MBP.lan:8443/api/v1/agent/Two words/config": (<class 'http.client.InvalidURL'>, InvalidURL("URL can't contain control characters. '/api/v1/agent/Two words/config' (found at least ' ')"), <traceback object at 0x12c85c5f0>)
```

### Expected behavior

Name can be different from address, and can be any printable Unicode string, including spaces and punctuation.

**Comment by rabits** [comment]
Yeah, need to check the interfaces better. Indeed since it uses the user input as the part of url - I need to handle that.

**Comment by rabits** [comment]
Ok, prepared the fix - could you please check it: https://1086-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.6-54966c9.zip - only the Addon side is affected and requires update + restart.

**Comment by meermanr** [comment]
I cloned the repo and checked out revision `54966c9` for all instances (Manager, Agent, and Blender plugin), and when I added "Robert's MBP" as an agent it seems to have worked, but displays with URI encoding in Blender's UI as "Robert%27s%20MBP".

<img width="290" alt="CleanShot 2020-12-28 at 19 13 55@2x" src="https://user-images.githubusercontent.com/318099/103237949-2527cf80-4941-11eb-9b66-16c915784dfb.png">

.. but when I tried "Run Image Task" it seems to just stay in `CREATED` state. I didn't automatically enter `RUNNING`, so I manually chose "Run Task" from the actions menu, and then saw these errors:

Manager log:

```
192.168.167.219 - - [28/Dec/2020 19:17:06] "GET /api/v1/info HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:06] "GET /api/v1/task HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:09] "GET /api/v1/resources HTTP/1.1" 200 -
DEBUG: Running task BackBedroommeasured-2012281908-1-F0I
DEBUG: Saving 1 tasks to disk
DEBUG: Saving 1 tasks to disk
DEBUG: Moved task to pending: "BackBedroommeasured-2012281908-1-F0I"
192.168.167.219 - - [28/Dec/2020 19:17:09] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I/run HTTP/1.1" 200 -
DEBUG: Execution watcher of task "BackBedroommeasured-2012281908-1-F0I" is started
INFO: Task BackBedroommeasured-2012281908-1-F0I started execution
DEBUG: Moved task from pending to running: "BackBedroommeasured-2012281908-1-F0I"
DEBUG: New workload for "Robert%27s%20MBP": {'project': 'Back Bedroom measured.blend', 'samples': 100, 'seed': 579708015, 'frame': 1, 'agents_num': 1, 'use_compositing_nodes': True, 'compose_filepath': '/tmp/0001.png', 'task_name': 'BackBedroommeasured-2012281908-1-F0I_0'}
DEBUG: Uploading 1 files to Agent "Robert%27s%20MBP" task "BackBedroommeasured-2012281908-1-F0I_0"
DEBUG: Creating Workers "Uploading to Agent "Robert%27s%20MBP" task "BackBedroommeasured-2012281908-1-F0I_0""
DEBUG: Starting ManagerTask "BackBedroommeasured-2012281908-1-F0I" results watcher
WARN: Communication issue with request to "https://Roberts-MBP.lan:9443/api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/status": HTTP 400 Bad Request: b'{"success": false, "message": "Unable to find task"}'
INFO: Retry request "https://Roberts-MBP.lan:9443/api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/status" in 1 sec
DEBUG: Uploading of "Back%20Bedroom%20measured.blend" to task "BackBedroommeasured-2012281908-1-F0I_0" completed
DEBUG: Uploading files to Agent "Robert%27s%20MBP" task "BackBedroommeasured-2012281908-1-F0I_0" completed
DEBUG: Sending workload to Agent "Robert%27s%20MBP" task "BackBedroommeasured-2012281908-1-F0I_0"
WARN: Communication issue with request to "https://Roberts-MBP.lan:9443/api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/config": HTTP 400 Bad Request: b'{"success": false, "message": "Error during task files fixing"}'
INFO: Retry request "https://Roberts-MBP.lan:9443/api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/config" in 1 sec
DEBUG: Deleting Workers "Uploading to Agent "Robert%27s%20MBP" task "BackBedroommeasured-2012281908-1-F0I_0""
DEBUG: task BackBedroommeasured-2012281908-1-F0I_0 state changed: CREATED
192.168.167.219 - - [28/Dec/2020 19:17:11] "GET /api/v1/info HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:11] "GET /api/v1/task HTTP/1.1" 200 -
ERROR: Communication exception - check the remote service for errors "https://Roberts-MBP.lan:9443/api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/config": (<class 'socket.timeout'>, timeout('The read operation timed out'), <traceback object at 0x12046a730>)
DEBUG: Run task "Robert%27s%20MBP" on Agent "BackBedroommeasured-2012281908-1-F0I_0"
DEBUG: task BackBedroommeasured-2012281908-1-F0I_0 state changed: ERROR
DEBUG: Retreive details about the task BackBedroommeasured-2012281908-1-F0I_0 execution
ERROR: The agent task BackBedroommeasured-2012281908-1-F0I_0 was ended with status "ERROR"
ERROR: Agent task "BackBedroommeasured-2012281908-1-F0I_0" ended up in ERROR state
DEBUG: Saving 1 tasks to disk
DEBUG: Stopped ManagerTask "BackBedroommeasured-2012281908-1-F0I" results watcher
DEBUG: Removing from running list ended task "BackBedroommeasured-2012281908-1-F0I"
DEBUG: Execution watcher of task "BackBedroommeasured-2012281908-1-F0I" is ended with state ERROR
192.168.167.219 - - [28/Dec/2020 19:17:17] "GET /api/v1/info HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:17] "GET /api/v1/task HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:22] "GET /api/v1/resources HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:22] "GET /api/v1/info HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:22] "GET /api/v1/task HTTP/1.1" 200 -
192.168.167.219 - - [28/Dec/2020 19:17:27] "GET /api/v1/info HTTP/1.1" 200 -
```

Agent STDIO:

```
192.168.167.148 - - [28/Dec/2020 19:17:07] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:08] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:09] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/status HTTP/1.1" 400 -
DEBUG: Creating new task BackBedroommeasured-2012281908-1-F0I_0
DEBUG: Created Agent task BackBedroommeasured-2012281908-1-F0I_0
192.168.167.148 - - [28/Dec/2020 19:17:09] "PUT /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/file/Back%2520Bedroom%2520measured.blend HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:09] "PUT /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/config HTTP/1.1" 400 -
192.168.167.148 - - [28/Dec/2020 19:17:09] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:10] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:10] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/messages HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:10] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:11] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:11] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:12] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:12] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:13] "PUT /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/config HTTP/1.1" 400 -
DEBUG: Running task BackBedroommeasured-2012281908-1-F0I_0
DEBUG: Moved task to pending: "BackBedroommeasured-2012281908-1-F0I_0"
192.168.167.148 - - [28/Dec/2020 19:17:13] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/run HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:13] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:13] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/details HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:13] "GET /api/v1/task/BackBedroommeasured-2012281908-1-F0I_0/messages HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:13] "GET /api/v1/status HTTP/1.1" 200 -
DEBUG: Execution watcher of task "BackBedroommeasured-2012281908-1-F0I_0" is started
INFO: Task BackBedroommeasured-2012281908-1-F0I_0 started execution
DEBUG: Files to use in workspace:
DEBUG: Moved task from pending to running: "BackBedroommeasured-2012281908-1-F0I_0"
DEBUG:   0aa212c773b5c9b72abf8fe18274be3bf3627063 Back%2520Bedroom%2520measured.blend
ERROR: Exception occurred during task "BackBedroommeasured-2012281908-1-F0I_0" execution: <class 'TypeError'>: startswith first arg must be str or a tuple of str, not NoneType
Exception in thread Thread-546:
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.91/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Applications/Blender.app/Contents/Resources/2.91/python/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/meermanr/Desktop/BlendNet.agent/BlendNet/AgentTask.py", line 64, in _executionWatcher
    self._parent._fc.workspaceClean(self.name())
  File "/Users/meermanr/Desktop/BlendNet.agent/BlendNet/FileCache.py", line 336, in workspaceClean
    self._workspace_blobs.pop(name)
KeyError: 'BackBedroommeasured-2012281908-1-F0I_0'

192.168.167.148 - - [28/Dec/2020 19:17:14] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:15] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:16] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:17] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:18] "GET /api/v1/status HTTP/1.1" 200 -
INFO: Writing 1 changed blobs metadata to disk
192.168.167.148 - - [28/Dec/2020 19:17:19] "GET /api/v1/status HTTP/1.1" 200 -
192.168.167.148 - - [28/Dec/2020 19:17:20] "GET /api/v1/status HTTP/1.1" 200 -
```

**Comment by meermanr** [comment]
I can't seem to remove this agent either. Copying the URL from the Manager's log and trying with `curl` it seems it doesn't understand the URI encoding?

```
meermanr@Roberts-Air ~ % curl --user None:None -X DELETE 'https://Roberts-MBP.lan:8443/api/v1/agent/Robert%2527s%2520MBP'
{"success": false, "message": "Unable to find the agent"}%
```

**Comment by rabits** [comment]
Yeah, I see - so it's not decoding the name on the Manager side... And on the file processor seems not working correctly due to not decoded from #130 fix... Oh those specsymbols... Ok, let me check what I can do here to unify that.

The thing is that the API have to decide - the string is needed to be decoded or not, because if the file or Agent name will actually contain %23 in the filename and it will be accidentally decoded - that will be some weird issue. Addon will always encode the filenames, but it's not actually known on the Manager or the Agent side. But not a big deal - if API calls is manually used with such files it's requirement for the user to encode the filename/agent name if it contains some specsymbols.

**Comment by rabits** [comment]
So, I just added unquote support to the SimpleREST framework, hopefully it will do the trick - could you please check if it will work for your case? https://1096-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.6-6f54c2f.zip - it will require update of Addon, Manager & Agent and restart.

**Comment by meermanr** [comment]
Thanks, `6f54c2f` seems to have fixed this for me:

<img width="304" alt="CleanShot 2020-12-30 at 02 01 31 of Blender's Back_Bedroom_measured blend" src="https://user-images.githubusercontent.com/318099/103325274-f72ab400-4a42-11eb-8cbb-e001454ac72e.png">

That said, it seems that my SSH Tunnel is causing timeouts which then cause the render job to abort entirely. I'll raise a new issue for that

**Comment by rabits** [comment]
Sure, thank you)

**Comment by meermanr** [comment]
> That said, it seems that my SSH Tunnel is causing timeouts which then cause the render job to abort entirely. I'll raise a new issue for that

OK turns out the agent at the other end of the SSH tunnel was using `origin/master` and not `6f54c2f`. Once I updated to the correct revision it began working. False alarm!

**Comment by rabits** [comment]
Great to hear it's working. Overall the network failure can cause unstable work of Manager-Agent pair, but I think it's better to wait until the real case will be here. Thank you for your time - you really helped to improve the BlendNet) Soon will release the 0.3.6 version with those fixes.

**Comment by meermanr** [comment]
> Thank you for your time - you really helped to improve the BlendNet

No no, thank *you* for fixing all these issues. I'm really enjoying being able to use all my computers to render faster. The live preview is just _awesome_. I also tried CrowdRender (even paid for a month of membership to give the latest version a try), but I have never gotten it to work reliably.

BlendNet works far better, and I like that it is asynchronous so I can kick off a render and keep modelling while it does its thing.
