### ISSUE TITLE
[BUG] Unable to see preview with 2.83.0

### ISSUE THREAD

**Issue by rabits** [state-of-the-art/BlendNet#23]
### Issue description:
Preview is not showing at least on 2.83.0

### Environment:
* **Application version**: master c183ae2
* **Blender UI version**: 2.83.0
* **Blender render version**: 2.83.0
* **OS**: Ubuntu 18.04

### Steps to reproduce:
1. Run Blender
2. Open project
3. Run manager
4. Run render of still picture
5. No previews
6. Result is ok

**Comment by rabits** [comment]
Some logs from the manager instance:
```
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]: 73.170.65.184 - - [08/Jun/2020 03:49:40] "GET /api/v1/task/testproject-2006080346-30-2Ok/status/result/preview HTTP/1.1" 200 -
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]: ----------------------------------------
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]: Exception happened during processing of request from ('73.170.65.184', 36346)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]: Traceback (most recent call last):
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/socketserver.py", line 650, in process_request_thread
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     self.finish_request(request, client_address)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/socketserver.py", line 360, in finish_request
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     self.RequestHandlerClass(request, client_address, self)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/socketserver.py", line 720, in __init__
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     self.handle()
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/http/server.py", line 426, in handle
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     self.handle_one_request()
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/http/server.py", line 414, in handle_one_request
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     method()
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blendnet/BlendNet/SimpleREST.py", line 177, in do_GET
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     self.processRequest()
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blendnet/BlendNet/SimpleREST.py", line 168, in processRequest
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     resp = proc[1]._runPathMethod(req_type, self)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blendnet/BlendNet/SimpleREST.py", line 85, in _runPathMethod
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     return func(req, parts)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blendnet/BlendNet/Server.py", line 196, in task_result_stream
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     req.wfile.write(chunk)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/socketserver.py", line 799, in write
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     self._sock.sendall(b)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/ssl.py", line 1034, in sendall
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     v = self.send(byte_view[count:])
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:   File "/srv/blender/2.83/python/lib/python3.7/ssl.py", line 1003, in send
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]:     return self._sslobj.write(data)
Jun  8 03:49:40 blendnet-ssmzsg-manager blender[2151]: ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by rabits** [comment]
And from the client:
```
ERROR: Communication exception - check the remote service for errors "https://104.197.37.243:8443/api/v1/task/testproject-2006080346-30-2Ok/status/
result/preview": <class 'FileNotFoundError'>
ERROR: Unable to load not existing result file "/home/user/Work/state-of-the-art/BlendNet.wiki/blendnet-test-project-2.83-v0.2/out/testproject-2006
080346-30-2Ok-preview.exr"
```

**Comment by rabits** [comment]
Yep, there is no issue with 2.81 client/worker

**Comment by rabits** [comment]
Hmmm... When I restarted the client and recreated the manager instance - the bug is gone... Not sure what it was, so seems hard to reproduce now.

**Comment by rabits** [comment]
Nope, it's here again...

**Comment by rabits** [comment]
Looks like it's coming from not created output directory on the client.

**Comment by rabits** [comment]
Yep, confirmed - the root cause is not created output directory

**Comment by rabits** [comment]
Fixed now
