### ISSUE TITLE
[BUG] Windows aws provider execution error

### ISSUE THREAD

**Issue by rabits** [state-of-the-art/BlendNet#75]
### Issue description:
Seems the Manager can't be started on Windows due to a bug with aws cli tool execution. Reported by @heizermeister

### Environment:
* **Application version**: 0.3.0
* **Blender client version**: [e.g. 2.83.0 (where addon is running)]
* **Blender worker version**: [e.g. 2.83.0 (which is used for manager/agents)]
* **OS**: Windows

### Additional context
```
DEBUG: Creating manager instance
DEBUG: Trying to get CA certificate from the bucket
INFO: Downloading file from "s3://blendnet-xdd6qy/ca.crt" ...
WARN: Downloading failed
DEBUG: Periodic update manager info False
INFO: Got image ami-084e4d31c6fce4746
INFO: Creating manager blendnet-xdd6qy-manager
WARN: Catched exception from "aws" provider execution of createInstanceManager: AWS tool returned 252 during execution of "('C:\Program Files\Amazon\AWSCLIV2\aws.exe', '--output', 'json', '--region', 'us-east-2', 'ec2', 'run-instances', '--tag-specifications', 'ResourceType=instance,Tags=[{Key=Name,Value=blendnet-xdd6qy-manager},{Key=Session,Value=xdd6qy},{Key=Type,Value=manager}]', '--image-id', 'ami-084e4d31c6fce4746', '--instance-type', 't3.micro', '--iam-instance-profile', '{"Name":"blendnet-manager"}', '--block-device-mappings', '[{"DeviceName": "/dev/xvda", "Ebs": {"DeleteOnTermination": true, "VolumeSize": 200, "VolumeType": "standard"}}]', '--security-groups', 'blendnet-manager', '--user-data', 'file://C:\Users\elviz\AppData\Local\Temp\tmpwsuuw4n8.sh')": b"\r\nError parsing parameter '--user-data': Unable to load paramfile file://C:\Users\elviz\AppData\Local\Temp\tmpwsuuw4n8.sh: [Errno 13] Permission denied: 'C:\\Users\\elviz\\AppData\\Local\\Temp\\tmpwsuuw4n8.sh'\r\n"
Traceback (most recent call last):
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 383, in createInstanceManager
data = _executeAwsTool(*options)
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 68, in _executeAwsTool
result.returncode, AWS_EXEC_PREFIX + args, result.stderr))
BlendNet-master.BlendNet.providers.aws.AwsToolException: AWS tool returned 252 during execution of "('C:\Program Files\Amazon\AWSCLIV2\aws.exe', '--output', 'json', '--region', 'us-east-2', 'ec2', 'run-instances', '--tag-specifications', 'ResourceType=instance,Tags=[{Key=Name,Value=blendnet-xdd6qy-manager},{Key=Session,Value=xdd6qy},{Key=Type,Value=manager}]', '--image-id', 'ami-084e4d31c6fce4746', '--instance-type', 't3.micro', '--iam-instance-profile', '{"Name":"blendnet-manager"}', '--block-device-mappings', '[{"DeviceName": "/dev/xvda", "Ebs": {"DeleteOnTermination": true, "VolumeSize": 200, "VolumeType": "standard"}}]', '--security-groups', 'blendnet-manager', '--user-data', 'file://C:\Users\elviz\AppData\Local\Temp\tmpwsuuw4n8.sh')": b"\r\nError parsing parameter '--user-data': Unable to load paramfile file://C:\Users\elviz\AppData\Local\Temp\tmpwsuuw4n8.sh: [Errno 13] Permission denied: 'C:\\Users\\elviz\\AppData\\Local\\Temp\\tmpwsuuw4n8.sh'\r\n"
DEBUG: Trying to get CA certificate from the bucket
INFO: Downloading file from "s3://blendnet-xdd6qy/ca.crt" ...
WARN: Downloading failed
DEBUG: Periodic update manager info False
DEBUG: Trying to get CA certificate from the bucket
INFO: Downloading file from "s3://blendnet-xdd6qy/ca.crt" ...
WARN: Downloading failed
DEBUG: Periodic update manager info False
DEBUG: Trying to get CA certificate from the bucket
INFO: Downloading file from "s3://blendnet-xdd6qy/ca.crt" ...
WARN: Downloading failed
```

**Comment by rabits** [comment]
Looks like the issue with the path for aws tool, it don't like "**file://C:\**Users\elviz\AppData\Local\Temp\tmpwsuuw4n8.sh" - need to run some tests on the win instance to figure out what it will like as a parameter.

**Comment by rabits** [comment]
According the docs there is another way - to use base64: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/run-instances.html

**Comment by rabits** [comment]
Looks like another one is here:
```
INFO: Uploading BlendNet logic to the bucket blendnet-xdd6qy
WARN: Catched exception from "aws" provider execution of createBucket: AWS tool returned 1 during execution of "('C:\Program Files\Amazon\AWSCLIV2\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'mb', 's3://blendnet-xdd6qy')": b'make_bucket failed: s3://blendnet-xdd6qy An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.\r\n'
Traceback (most recent call last):
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 593, in createBucket
_executeAwsTool('s3', 'mb', 's3://' + bucket_name)
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 69, in _executeAwsTool
result.returncode, AWS_EXEC_PREFIX + args, result.stderr))
BlendNet-master.BlendNet.providers.aws.AwsToolException: AWS tool returned 1 during execution of "('C:\Program Files\Amazon\AWSCLIV2\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'mb', 's3://blendnet-xdd6qy')": b'make_bucket failed: s3://blendnet-xdd6qy An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.\r\n'
DEBUG: Creating Workers "Uploading BlendNet logic to the bucket "blendnet-xdd6qy""
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
WARN: Catched exception from "aws" provider execution of uploadDataToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
Traceback (most recent call last):
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execP
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
Traceback (most recent call last):
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
Traceback (most recent call last):
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
Traceback (most recent call last):
Traceback (most recent call last):
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
Traceback (most recent call last):
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
return getattr(modules[selected_provider], func)(args, *kwargs)
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 605, in uploadFileToBucket
dest_path = pathlib.PurePath(dest_path).as_posix()
NameError: name 'pathlib' is not defined
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: name 'pathlib' is not defined
File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in
...
```
