### ISSUE TITLE
[BUG] Windows don't want to upload temp file to S3 via aws

### ISSUE THREAD

**Issue by rabits** [state-of-the-art/BlendNet#79]
### Issue description:
Seems some security don't allow aws subprogramm to use temp file created by blender itself:
```
WARN: Catched exception from "aws" provider execution of createBucket: AWS tool returned 1 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'mb', 's3://blendnet-xdd6qy')": b'make_bucket failed: s3://blendnet-xdd6qy An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.\r\n'
Traceback (most recent call last):
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
    return getattr(modules[selected_provider], func)(*args, **kwargs)
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 594, in createBucket
    _executeAwsTool('s3', 'mb', 's3://' + bucket_name)
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 70, in _executeAwsTool
    result.returncode, AWS_EXEC_PREFIX + args, result.stderr))
BlendNet-master.BlendNet.providers.aws.AwsToolException: AWS tool returned 1 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'mb', 's3://blendnet-xdd6qy')": b'make_bucket failed: s3://blendnet-xdd6qy An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.\r\n'
DEBUG: Creating Workers "Uploading BlendNet logic to the bucket "blendnet-xdd6qy""
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/agent.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/manager.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/__init__.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/.circleci/test_script_addon.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/BlendNet/addon.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/BlendNet/Agent.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/BlendNet/AgentClient.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/blendnet/BlendNet/AgentTask.py" ...
INFO: Uploading file to "s3://blendnet-xdd6qy/work_manager/manager.json" ...
WARN: Catched exception from "aws" provider execution of uploadDataToBucket: AWS tool returned 2 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'cp', 'C:\\Users\\elviz\\AppData\\Local\\Temp\\tmp1uf_otq2', 's3://blendnet-xdd6qy/work_manager/manager.json')": b'warning: Skipping file C:\\Users\\elviz\\AppData\\Local\\Temp\\tmp1uf_otq2. File/Directory is not readable.\r\n'
Traceback (most recent call last):
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
    return getattr(modules[selected_provider], func)(*args, **kwargs)
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 621, in uploadDataToBucket
    uploadFileToBucket(tmp_file.name, bucket_name, dest_path)
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 611, in uploadFileToBucket
    _executeAwsTool('s3', 'cp', path, dest_path)
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 70, in _executeAwsTool
    result.returncode, AWS_EXEC_PREFIX + args, result.stderr))
BlendNet-master.BlendNet.providers.aws.AwsToolException: AWS tool returned 2 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'cp', 'C:\\Users\\elviz\\AppData\\Local\\Temp\\tmp1uf_otq2', 's3://blendnet-xdd6qy/work_manager/manager.json')": b'warning: Skipping file C:\\Users\\elviz\\AppData\\Local\\Temp\\tmp1uf_otq2. File/Directory is not readable.\r\n'
DEBUG: Trying to get CA certificate from the bucket
INFO: Downloading file from "s3://blendnet-xdd6qy/ca.crt" ...
WARN: Catched exception from "aws" provider execution of uploadFileToBucket: AWS tool returned 1 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'cp', 'C:\\Users\\elviz\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons\\BlendNet-master\\__init__.py', 's3://blendnet-xdd6qy/blendnet/__init__.py')": b'upload failed: ..\\..\\..\\Users\\elviz\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons\\BlendNet-master\\__init__.py to s3://blendnet-xdd6qy/blendnet/__init__.py An error occurred (IllegalLocationConstraintException) when calling the PutObject operation: The eu-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.\r\n'
Traceback (most recent call last):
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
    return getattr(modules[selected_provider], func)(*args, **kwargs)
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 611, in uploadFileToBucket
    _executeAwsTool('s3', 'cp', path, dest_path)
  File "C:\Users\elviz\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendNet-master\BlendNet\providers\aws\__init__.py", line 70, in _executeAwsTool
    result.returncode, AWS_EXEC_PREFIX + args, result.stderr))
BlendNet-master.BlendNet.providers.aws.AwsToolException: AWS tool returned 1 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-east-2', 's3', 'cp', 'C:\\Users\\elviz\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons\\BlendNet-master\\__init__.py', 's3://blendnet-xdd6qy/blendnet/__init__.py')": b'upload failed: ..\\..\\..\\Users\\elviz\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons\\BlendNet-master\\__init__.py to s3://blendnet-xdd6qy/blendnet/__init__.py An error occurred (IllegalLocationConstraintException) when calling the PutObject ope
```

### Environment:
* **Application version**: 0.3.0
* **OS**: Windows

**Comment by rabits** [comment]
Ok, here is 2 issues I see actually:
* first one is with access the tempfile (because windows don't allow to access the temp file from one process to a subprocess)
* second one with specify the region for s3 commands - looks like not required.

First one could be solved by stdin:
```
echo asd | aws s3 cp - s3://mybucket/stream.txt
```
