### ISSUE TITLE
[BUG] AWS provider doesn't show service/node logs on windows

### ISSUE THREAD

**Issue by rabits** [state-of-the-art/BlendNet#81]
### Issue description:
Seems there is no way to get the logs on windows from the service or node for AWS...

### Environment:
* **Application version**: 0.3.0
* **OS**: Windows

**Comment by rabits** [comment]
Ok, prepared a fix, but looks like on windows even AWS tool is not working correctly with outputting the log:
```
DEBUG: Periodic update manager info True
WARN: Catched exception from "aws" provider execution of getNodeLog: AWS tool returned 255 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-west-1', 'ec2', 'get-console-output', '--instance-id', 'i-064f866083905a5bd')": b"\r\n'charmap' codec can't encode character '\\u2192' in position 66745: character maps to <undefined>\r\n"
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendnet\BlendNet\providers\__init__.py", line 72, in _execProviderFunc
    return getattr(modules[selected_provider], func)(*args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendnet\BlendNet\providers\aws\__init__.py", line 696, in getNodeLog
    '--instance-id', instance_id)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendnet\BlendNet\providers\aws\__init__.py", line 75, in _executeAwsTool
    result.returncode, AWS_EXEC_PREFIX + args, result.stderr))
blendnet.BlendNet.providers.aws.AwsToolException: AWS tool returned 255 during execution of "('C:\\Program Files\\Amazon\\AWSCLIV2\\aws.exe', '--output', 'json', '--region', 'us-west-1', 'ec2', 'get-console-output', '--instance-id', 'i-064f866083905a5bd')": b"\r\n'charmap' codec can't encode character '\\u2192' in position 66745: character maps to <undefined>\r\n"
```

**Comment by rabits** [comment]
Prepared a bug for aws-cli tool: aws/aws-cli#5558

**Comment by rabits** [comment]
The workaround for this issue is:
> The current solution is to enable UTF-8 as in the Windows system locale, as described here:
> 
> https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096
