### ISSUE TITLE
[FEATURE] Ability to run Manager/Agents on Windows

### ISSUE THREAD

**Issue by rabits** [state-of-the-art/BlendNet#84]
### Is your feature request related to a problem? Please describe.
Right now Manager & Agents are running on Linux (probably on Mac's too) - but it will be great to support win platform too.

reported by: @partialblueshift

**Comment by rabits** [comment]
Report from @partialblueshift :
```
PS C:_3D\blender-2.83.5-windows64> .\blender.exe -b -noaudio -P .\2.83\scripts\addons\blendnet\manager.py
Blender 2.83.5 (hash c2b144df395f built 2020-08-19 04:10:17)
Read prefs: C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: C:_3D\blender-2.83.5-windows64\2.83\python
INFO: Found provider "aws"
INFO: Found provider "gcp"
'gcloud' is not recognized as an internal or external command,
operable program or batch file.
INFO: Found provider "local"
WARN: Metadata is not available
INFO: Importing base from "local" provider
DEBUG: selected provider: local
INFO: Search for blender embedded certificates...
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:_3D\blender-2.83.5-windows64.\2.83\scripts\addons\blendnet\manager.py", line 11, in <module>
faulthandler.register(signal.SIGUSR1)
AttributeError: module 'faulthandler' has no attribute 'register'
DEBUG: Delete BlendNet render
```

Looks like faulthandler is supported only on nix systems.

**Comment by rabits** [comment]
So basically the manager & agent is working on win with minimal changes, but windows don't allow to override the existing file.
```
File "C:_3D\render_farm..\blender-2.83.5-windows64\2.83\scripts\addons\blendnet\BlendNet\FileCache.py", line 239, in blobStoreStream
os.rename(received[1], blob_path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\_3D\render_farm\BlendNet_cache\tmp\c690ce4e1d8dd2ef3607a2d5f995712edfc4e2e1' -> 'C:\_3D\render_farm\BlendNet_cache\blobs\c6\c690ce4e1d8dd2ef3607a2d5f995712edfc4e2e1'
```

**Comment by rabits** [comment]
Quite the same issue with the Agent when it tries to write the preview file...

**Comment by rabits** [comment]
Yeah, so `os.rename()` on windows will not replace the target path, but raises the exception. Adding the check/remove before the renaming fixes the issue, but how to swap atomary looks impossible on windows.

**Comment by rabits** [comment]
Almost any operation with files on Windows could raise exception, `blobRemove` could do that - and the entire merge process will fail...

**Comment by rabits** [comment]
Compose script had issues as well - for some reason it can't properly parse the output to find the compose filepath...
